# Generated by Django 2.0.3 on 2020-11-11 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='img',
            field=models.ImageField(default='', upload_to='images/'),
        ),
        migrations.AddField(
            model_name='employee',
            name='title',
            field=models.CharField(default=-1.0, max_length=200),
            preserve_default=False,
        ),
    ]
