# Generated by Django 2.0.3 on 2020-11-14 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_auto_20201111_0511'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='img',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='title',
        ),
    ]
