# Generated by Django 2.0.3 on 2020-11-26 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_auto_20201114_0943'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='profilePic',
            field=models.ImageField(default='', upload_to='images/'),
        ),
    ]
